import type { MenuItem } from '@/lib/types';

export const menuItems: MenuItem[] = [
  {
    id: 1,
    name: 'Classic Veggie Burger',
    description: 'A delicious veggie patty with fresh lettuce, tomatoes, and our special sauce.',
    price: 150,
    category: 'Burgers',
    image: 'https://picsum.photos/seed/burger/600/400',
    imageHint: 'veggie burger',
  },
  {
    id: 2,
    name: 'Masala Fries',
    description: 'Crispy fries tossed in a secret blend of Indian spices.',
    price: 80,
    category: 'Sides',
    image: 'https://picsum.photos/seed/fries/600/400',
    imageHint: 'masala fries',
  },
  {
    id: 3,
    name: 'Paneer Tikka Wrap',
    description: 'Grilled paneer tikka, crunchy veggies, and mint chutney wrapped in a soft tortilla.',
    price: 180,
    category: 'Wraps',
    image: 'https://picsum.photos/seed/wrap/600/400',
    imageHint: 'paneer wrap',
  },
  {
    id: 4,
    name: 'Mango Lassi',
    description: 'A refreshing and creamy yogurt-based drink with sweet mango pulp.',
    price: 90,
    category: 'Beverages',
    image: 'https://picsum.photos/seed/lassi/600/400',
    imageHint: 'mango lassi',
  },
  {
    id: 5,
    name: 'Samosa Chaat',
    description: 'Crushed samosas topped with yogurt, tamarind and mint chutneys, and spices.',
    price: 120,
    category: 'Chaat',
    image: 'https://picsum.photos/seed/chaat/600/400',
    imageHint: 'samosa chaat',
  },
  {
    id: 6,
    name: 'Gulab Jamun',
    description: 'Soft, spongy berry-sized balls soaked in rose-flavored sugar syrup.',
    price: 70,
    category: 'Desserts',
    image: 'https://picsum.photos/seed/dessert/600/400',
    imageHint: 'gulab jamun',
  },
   {
    id: 7,
    name: 'Margherita Pizza',
    description: 'Classic pizza with fresh tomatoes, mozzarella cheese, and basil.',
    price: 250,
    category: 'Pizza',
    image: 'https://picsum.photos/seed/pizza/600/400',
    imageHint: 'margherita pizza',
  },
  {
    id: 8,
    name: 'Coke',
    description: 'Chilled Coca-Cola to quench your thirst.',
    price: 40,
    category: 'Beverages',
    image: 'https://picsum.photos/seed/coke/600/400',
    imageHint: 'coke can',
  },
];
